version: '2'
services:
  redis-cluster:
    build:
      context: .
      args:
        redis_version: '3.2.9'
    hostname: server
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "7006:7006"
      - "7007:7007"
    networks:
      - one
      - two

networks:
  one:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
  two:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
